// Mocks generated by Mockito 5.3.2 from annotations
// in spoonacular/test/unit_tests/get_recipes_use_case_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spoonacular/src/data/models/ingredient_model.dart' as _i5;
import 'package:spoonacular/src/data/models/recipe_model.dart' as _i4;
import 'package:spoonacular/src/data/models/similar_recipe_model.dart' as _i6;
import 'package:spoonacular/src/data/repositories/recipes_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RecipesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipesRepository extends _i1.Mock implements _i2.RecipesRepository {
  MockRecipesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RecipeModel>> getRecipes({required String? endpoint}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipes,
          [],
          {#endpoint: endpoint},
        ),
        returnValue:
            _i3.Future<List<_i4.RecipeModel>>.value(<_i4.RecipeModel>[]),
      ) as _i3.Future<List<_i4.RecipeModel>>);
  @override
  _i3.Future<List<_i5.IngredientModel>> getRecipeIngredients(
          {required String? endpoint}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeIngredients,
          [],
          {#endpoint: endpoint},
        ),
        returnValue: _i3.Future<List<_i5.IngredientModel>>.value(
            <_i5.IngredientModel>[]),
      ) as _i3.Future<List<_i5.IngredientModel>>);
  @override
  _i3.Future<String> getRecipeNutritionLabel({required String? endpoint}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeNutritionLabel,
          [],
          {#endpoint: endpoint},
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
  @override
  _i3.Future<List<_i6.SimilarRecipeModel>> getSimilarRecipes(
          {required String? endpoint}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSimilarRecipes,
          [],
          {#endpoint: endpoint},
        ),
        returnValue: _i3.Future<List<_i6.SimilarRecipeModel>>.value(
            <_i6.SimilarRecipeModel>[]),
      ) as _i3.Future<List<_i6.SimilarRecipeModel>>);
}
